# Конфигурация gRPC PubSub сервиса

# Порт для прослушивания
port: 50051

# Настройки логирования
log_file: "pubsub_service.log"  # Путь к файлу логов, если не нужно - оставить пустым
log_to_console: true            # Выводить логи в консоль